# Generated by Django 5.2.8 on 2026-09-05 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='author_timestamp',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='commit',
            name='author_timezone',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='commit',
            name='committer_email',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='commit',
            name='committer_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='commit',
            name='committer_timestamp',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='commit',
            name='committer_timezone',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='repository',
            name='object_format',
            field=models.CharField(choices=[('legacy', 'Legacy'), ('sha256', 'SHA-256')], default='legacy', max_length=10),
        ),
        migrations.AlterField(
            model_name='commit',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commit',
            name='sha',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='commit',
            unique_together={('repository', 'sha')},
        ),
        migrations.CreateModel(
            name='PersonalAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('can_write', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.repository')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GitMigrationMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_oid', models.CharField(max_length=64)),
                ('new_oid', models.CharField(max_length=64)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_migration_map', to='api.repository')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('repository', 'old_oid'), name='git_migration_repository_oid')],
            },
        ),
        migrations.CreateModel(
            name='GitObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=6)),
                ('size', models.PositiveBigIntegerField()),
                ('data', models.BinaryField()),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_objects', to='api.repository')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('repository', 'oid'), name='git_object_repository_oid')],
            },
        ),
        migrations.CreateModel(
            name='GitRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('target', models.CharField(max_length=64)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_refs', to='api.repository')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('repository', 'name'), name='git_ref_repository_name')],
            },
        ),
    ]
