# Generated by Django 5.2.8 on 2026-09-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_commit_author_timestamp_commit_author_timezone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='target_oid',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='tag',
            name='target_type',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
