# Generated by Django 5.2.8 on 2026-05-04 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_repository_commit_branch_blob_tree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('commit_sha', models.CharField(max_length=40)),
                ('message', models.TextField(blank=True)),
                ('annotated', models.BooleanField(default=False)),
                ('tagger_name', models.CharField(blank=True, max_length=255)),
                ('tagger_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='api.repository')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['name'],
                'unique_together': {('repository', 'name')},
            },
        ),
    ]
