# Generated by Django 5.2.8 on 2026-09-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tag_target_oid_tag_target_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['is_private', '-updated_at'], name='api_reposit_is_priv_9f714c_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['name'], name='api_reposit_name_a7f264_idx'),
        ),
    ]
