# Generated by Django 5.2.8 on 2026-05-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blob',
            name='sha',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='branch',
            name='commit_sha',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='commit',
            name='sha',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='commit',
            name='tree_sha',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='tag',
            name='commit_sha',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='tree',
            name='sha',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
