# Generated by Django 5.2.8 on 2026-07-01 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_blob_sha_alter_branch_commit_sha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('write', 'Write'), ('read', 'Read')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.repository')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'repository member',
                'verbose_name_plural': 'repository members',
                'unique_together': {('repository', 'user')},
            },
        ),
    ]
