# Generated by Django 5.2.8 on 2026-09-05 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_repository_api_reposit_is_priv_9f714c_idx_and_more'),
        ('api', '0008_repair_user_username_column'),
    ]

    operations = [
    ]
